### PR TITLE
Take advantage of contiguous memory storage in deques

### PR DESCRIPTION
**Pull request by Ironholds**
A lot of the treegraph-related C++ takes the form of something like:

```c++
std::vector < Node* > x;
for(unsigned int i = 0; i < y.size(); i++){
    x.push_back(y[i])
}
```

The problem is that a vector is contiguous memory; every time you push_back() on it you're committing the same anti-patterns you'd get appending to a vector in R (recreating it anew each time). Deques are much the same for these purposes (albeit with a slightly larger memory footprint) but are non-contiguous, so push_back() operations are much much much faster. So I've switched out vectors for deques.

It compiles, although I'm not *entirely* sure if it works since there are no unit tests that I can see and the functions that call the treegraph code don't seem to have examples...

### CODE REVIEW

**Comment by thomasp85** [comment]
I think that a lot of places the gain is insignificant (e.g. I don't expect the number of children to surpass the preallocation in `std::vector`) still, it doesn't hurt and after writing this code I have generally defaulted to `std::deque`. I'll review in more detail and merge - there should be examples in `geom_treemap` calling this code so I don't foresee to many problems

**Comment by klmr** [comment]
@Ironholds 

> every time you push_back() on it you're committing the same anti-patterns you'd get appending to a vector in R (recreating it anew each time).

This isn’t how `std::vector` in C++ works. Unlike R vectors, `std::vector`’s `push_back` member function has amortised O(1) runtime, even without manual preallocation. In fact, this is the default implementation in most programming languages (including Python’s `list`, Java’s/C#’s sequential containers, etc.).

**Comment by Ironholds** [comment]
Interesting; all the benchmarks I've ran show it can be an improvement (although it depends on the type and amount now C++ does some certain amount of over-enthusiastic allocation). Ah well!

**Comment by thomasp85** [comment]
Closing for now - these layouts are not any bottleneck anyway

**Pull request closed without merging**
